In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import math
w=torch.empty(3,5)
w

tensor([[1.6923e+09, 3.0858e-41, 1.6923e+09, 3.0858e-41, 3.3631e-44],
        [2.3849e+32, 4.8620e+04, 3.0858e-41, 1.4013e-45, 2.7486e+20],
        [7.1561e+22, 2.1715e-18, 5.6052e-45, 0.0000e+00, 5.6052e-45]])

In [2]:
nn.init.zeros_(w)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [3]:
nn.init.uniform_(w,1,10)

tensor([[1.6037, 8.2502, 4.1045, 6.3071, 2.6560],
        [8.4190, 9.0567, 8.6271, 5.1990, 1.9413],
        [4.1436, 5.9750, 1.4277, 6.0143, 7.0558]])

In [4]:
w.reshape(-1)

tensor([1.6037, 8.2502, 4.1045, 6.3071, 2.6560, 8.4190, 9.0567, 8.6271, 5.1990,
        1.9413, 4.1436, 5.9750, 1.4277, 6.0143, 7.0558])

In [110]:
w.view(-1,5)

tensor([[          0,           0,           0, -2147483648,           0],
        [          0,           0, -2147483648,           0, -2147483648],
        [-2147483648, -2147483648, -2147483648, -2147483648,           0]],
       dtype=torch.int32)

In [34]:
output=F.log_softmax(w,dim=1)
output

tensor([[-5.5315, -2.3640, -0.3437, -8.0363, -1.6475],
        [-0.7939, -3.3018, -4.6061, -1.2516, -1.5368],
        [-1.4727, -8.6062, -7.8745, -0.2620, -7.4247]])

In [117]:
m=nn.Dropout(0.5)
print(m(w))
# print(w*m(w.float()))

tensor([[ 4.2628,  0.0000,  8.3454, 18.2079,  0.0000],
        [14.0331,  0.0000, 19.3789, 18.6012,  0.0000],
        [ 6.2739,  0.0000,  4.2828, 11.8688, 18.7435]])


In [36]:
raw_output = torch.randn(2, 3)
raw_output

tensor([[ 1.0053, -0.3202,  0.2920],
        [-0.4966,  1.0894,  0.3824]])

In [37]:
log_probs = F.log_softmax(raw_output, dim=1)
log_probs

tensor([[-0.5628, -1.8884, -1.2762],
        [-2.1153, -0.5294, -1.2363]])

In [42]:
target_labels = torch.tensor([0, 2])
loss = F.nll_loss(log_probs, target_labels)
loss

tensor(0.8996)

In [74]:
torch.arange(0,20,dtype=torch.float).unsqueeze(0).unsqueeze(0).size()

torch.Size([1, 1, 20])

In [92]:
torch.arange(0,20,dtype=torch.float).unsqueeze(0).size()

torch.Size([1, 20])

In [76]:
torch.arange(0,20,dtype=torch.float).unsqueeze(1).size()


torch.Size([20, 1])

In [97]:
torch.arange(0,20,dtype=torch.float).unsqueeze(0).transpose(0,1).size()

torch.Size([1, 20])

In [94]:
torch.arange(0,20,dtype=torch.float).unsqueeze(1).transpose(0,1).size()

torch.Size([1, 20])

In [77]:
torch.arange(0,20,2)

tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [81]:
pe=torch.eye(10,15)
pe

tensor([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.]])

In [85]:
pe[:,0::2]
#even index

tensor([[1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]])

In [86]:
pe[:,1::2]
#odd index

tensor([[0., 0., 0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0.]])

In [127]:
mask=(torch.triu(torch.ones(5,5))==1).t()
mask

tensor([[ True, False, False, False, False],
        [ True,  True, False, False, False],
        [ True,  True,  True, False, False],
        [ True,  True,  True,  True, False],
        [ True,  True,  True,  True,  True]])

In [130]:
mask.float().masked_fill(mask==0,float('-inf')).masked_fill(mask==1,float(0.0))

tensor([[0., -inf, -inf, -inf, -inf],
        [0., 0., -inf, -inf, -inf],
        [0., 0., 0., -inf, -inf],
        [0., 0., 0., 0., -inf],
        [0., 0., 0., 0., 0.]])

In [132]:
mask.size(0)

5

In [8]:
torch.arange(5,dtype=torch.float).unsqueeze(1)

tensor([[0.],
        [1.],
        [2.],
        [3.],
        [4.]])

In [40]:
position=torch.arange(10,dtype=torch.float).unsqueeze(1)
position,position.size()

(tensor([[0.],
         [1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([10, 1]))

In [35]:
import math
div_term=torch.exp(-math.log(10000.0)*(torch.arange(0,10,step=2,dtype=torch.float)/10))

In [38]:
div_term,div_term.size()

(tensor([1.0000e+00, 1.5849e-01, 2.5119e-02, 3.9811e-03, 6.3096e-04]),
 torch.Size([5]))

In [43]:
pe_1=div_term*position
pe_1,pe.size()

(tensor([[0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
         [1.0000e+00, 1.5849e-01, 2.5119e-02, 3.9811e-03, 6.3096e-04],
         [2.0000e+00, 3.1698e-01, 5.0238e-02, 7.9621e-03, 1.2619e-03],
         [3.0000e+00, 4.7547e-01, 7.5357e-02, 1.1943e-02, 1.8929e-03],
         [4.0000e+00, 6.3396e-01, 1.0048e-01, 1.5924e-02, 2.5238e-03],
         [5.0000e+00, 7.9245e-01, 1.2559e-01, 1.9905e-02, 3.1548e-03],
         [6.0000e+00, 9.5094e-01, 1.5071e-01, 2.3886e-02, 3.7857e-03],
         [7.0000e+00, 1.1094e+00, 1.7583e-01, 2.7867e-02, 4.4167e-03],
         [8.0000e+00, 1.2679e+00, 2.0095e-01, 3.1849e-02, 5.0477e-03],
         [9.0000e+00, 1.4264e+00, 2.2607e-01, 3.5830e-02, 5.6786e-03]]),
 torch.Size([10, 1, 5]))

In [44]:
pe=torch.zeros(10,1,10)
pe,pe.size()

(tensor([[[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],
 
         [[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],
 
         [[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],
 
         [[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],
 
         [[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],
 
         [[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],
 
         [[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],
 
         [[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],
 
         [[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],
 
         [[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]]]),
 torch.Size([10, 1, 10]))

In [45]:
pe[:,0,0::2]=torch.sin(pe_1)
pe

tensor([[[ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
           0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00]],

        [[ 8.4147e-01,  0.0000e+00,  1.5783e-01,  0.0000e+00,  2.5116e-02,
           0.0000e+00,  3.9811e-03,  0.0000e+00,  6.3096e-04,  0.0000e+00]],

        [[ 9.0930e-01,  0.0000e+00,  3.1170e-01,  0.0000e+00,  5.0217e-02,
           0.0000e+00,  7.9621e-03,  0.0000e+00,  1.2619e-03,  0.0000e+00]],

        [[ 1.4112e-01,  0.0000e+00,  4.5775e-01,  0.0000e+00,  7.5285e-02,
           0.0000e+00,  1.1943e-02,  0.0000e+00,  1.8929e-03,  0.0000e+00]],

        [[-7.5680e-01,  0.0000e+00,  5.9234e-01,  0.0000e+00,  1.0031e-01,
           0.0000e+00,  1.5924e-02,  0.0000e+00,  2.5238e-03,  0.0000e+00]],

        [[-9.5892e-01,  0.0000e+00,  7.1207e-01,  0.0000e+00,  1.2526e-01,
           0.0000e+00,  1.9904e-02,  0.0000e+00,  3.1548e-03,  0.0000e+00]],

        [[-2.7942e-01,  0.0000e+00,  8.1396e-01,  0.0000e+00,  1.5014e-01,
       

In [46]:
pe[:,0,1::2]=torch.cos(pe_1)
pe,pe.size()

(tensor([[[ 0.0000e+00,  1.0000e+00,  0.0000e+00,  1.0000e+00,  0.0000e+00,
            1.0000e+00,  0.0000e+00,  1.0000e+00,  0.0000e+00,  1.0000e+00]],
 
         [[ 8.4147e-01,  5.4030e-01,  1.5783e-01,  9.8747e-01,  2.5116e-02,
            9.9968e-01,  3.9811e-03,  9.9999e-01,  6.3096e-04,  1.0000e+00]],
 
         [[ 9.0930e-01, -4.1615e-01,  3.1170e-01,  9.5018e-01,  5.0217e-02,
            9.9874e-01,  7.9621e-03,  9.9997e-01,  1.2619e-03,  1.0000e+00]],
 
         [[ 1.4112e-01, -9.8999e-01,  4.5775e-01,  8.8908e-01,  7.5285e-02,
            9.9716e-01,  1.1943e-02,  9.9993e-01,  1.8929e-03,  1.0000e+00]],
 
         [[-7.5680e-01, -6.5364e-01,  5.9234e-01,  8.0569e-01,  1.0031e-01,
            9.9496e-01,  1.5924e-02,  9.9987e-01,  2.5238e-03,  1.0000e+00]],
 
         [[-9.5892e-01,  2.8366e-01,  7.1207e-01,  7.0211e-01,  1.2526e-01,
            9.9212e-01,  1.9904e-02,  9.9980e-01,  3.1548e-03,  1.0000e+00]],
 
         [[-2.7942e-01,  9.6017e-01,  8.1396e-01,  5.8092e-01,  

In [48]:
pe[:3],pe[:3].size()

(tensor([[[ 0.0000e+00,  1.0000e+00,  0.0000e+00,  1.0000e+00,  0.0000e+00,
            1.0000e+00,  0.0000e+00,  1.0000e+00,  0.0000e+00,  1.0000e+00]],
 
         [[ 8.4147e-01,  5.4030e-01,  1.5783e-01,  9.8747e-01,  2.5116e-02,
            9.9968e-01,  3.9811e-03,  9.9999e-01,  6.3096e-04,  1.0000e+00]],
 
         [[ 9.0930e-01, -4.1615e-01,  3.1170e-01,  9.5018e-01,  5.0217e-02,
            9.9874e-01,  7.9621e-03,  9.9997e-01,  1.2619e-03,  1.0000e+00]]]),
 torch.Size([3, 1, 10]))

In [49]:
import torch.nn as nn
src_mask=nn.Transformer.generate_square_subsequent_mask(5)
src_mask
"""
Generate a square causal mask for the sequence.
The masked positions are filled with float('-inf').
Unmasked positions are filled with float(0.0).
"""

tensor([[0., -inf, -inf, -inf, -inf],
        [0., 0., -inf, -inf, -inf],
        [0., 0., 0., -inf, -inf],
        [0., 0., 0., 0., -inf],
        [0., 0., 0., 0., 0.]])

In [18]:
for batch,i in enumerate(range(0,10,2)):
    print(batch,i)

0 0
1 2
2 4
3 6
4 8


In [10]:
import torch
data=torch.arange(10)
data=data.view(2,5)
data

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [12]:
data.t()

tensor([[0, 5],
        [1, 6],
        [2, 7],
        [3, 8],
        [4, 9]])

In [23]:
data=torch.randn((2,3,5))
data

tensor([[[-0.6700, -0.9853,  0.1164, -0.4258, -0.2752],
         [ 0.1639,  1.0277,  1.6507,  0.1821,  2.2228],
         [-0.3210,  0.0952, -0.0935, -0.3677,  0.5275]],

        [[-1.5541, -0.3386, -0.6610,  0.9839,  0.1680],
         [ 0.3314, -1.5261, -0.3260, -0.1305,  1.2177],
         [-0.6113, -1.5914,  0.2263, -2.5556,  0.7272]]])

In [24]:
data.view(-1,5)

tensor([[-0.6700, -0.9853,  0.1164, -0.4258, -0.2752],
        [ 0.1639,  1.0277,  1.6507,  0.1821,  2.2228],
        [-0.3210,  0.0952, -0.0935, -0.3677,  0.5275],
        [-1.5541, -0.3386, -0.6610,  0.9839,  0.1680],
        [ 0.3314, -1.5261, -0.3260, -0.1305,  1.2177],
        [-0.6113, -1.5914,  0.2263, -2.5556,  0.7272]])

In [33]:
tensor=torch.tensor([0.1,0.3,0.1],dtype=float)
l2_norm=torch.norm(tensor,2)
l2_norm

tensor(0.3317, dtype=torch.float64)

In [32]:
from tempfile import TemporaryDirectory
TemporaryDirectory()

<TemporaryDirectory '/tmp/tmpeezstull'>

In [3]:
w,w.size()

(tensor([[1.6923e+09, 3.0858e-41, 1.6923e+09, 3.0858e-41, 3.3631e-44],
         [2.3849e+32, 4.8620e+04, 3.0858e-41, 1.4013e-45, 2.7486e+20],
         [7.1561e+22, 2.1715e-18, 5.6052e-45, 0.0000e+00, 5.6052e-45]]),
 torch.Size([3, 5]))

In [5]:
log_probs=F.log_softmax(w,dim=1)
log_probs

tensor([[ 0.0000e+00, -1.6923e+09, -1.5360e+04, -1.6923e+09, -1.6923e+09],
        [ 0.0000e+00, -2.3849e+32, -2.3849e+32, -2.3849e+32, -2.3849e+32],
        [ 0.0000e+00, -7.1561e+22, -7.1561e+22, -7.1561e+22, -7.1561e+22]])

In [64]:
prob=nn.Softmax(dim=1)(w)
prob

tensor([[1., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0.]])

In [81]:
nn.Softmax()(torch.tensor([0.0,0.0,0.0]))

/home/adminroot/miniconda3/envs/distill_data/lib/python3.11/site-packages/torch/nn/modules/module.py:1518: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  return self._call_impl(*args, **kwargs)


tensor([0.3333, 0.3333, 0.3333])

In [65]:
criterion=nn.CrossEntropyLoss()
criterion(prob,torch.tensor([0,0,0],dtype=torch.long))

tensor(0.9048)

In [36]:
criterion(log_probs,torch.tensor([0,0,0],dtype=torch.long))

tensor(0.)

In [53]:
criterion(prob[2].unsqueeze(0),torch.tensor([3],dtype=torch.long))

tensor(1.9048)

In [54]:
criterion(prob[0].unsqueeze(0),torch.tensor([0],dtype=torch.long))

tensor(0.9048)

In [97]:
criterion(w,torch.tensor([0,0,0],dtype=torch.long))

tensor(0.)

In [99]:
import math
math.exp(1)


2.718281828459045

In [100]:
math.exp(0)

1.0

In [101]:
2.718281828459045+4

6.718281828459045

In [104]:
2.718281828459045/6.718281828459045

0.40460967519168967

In [105]:
1.0/6.718281828459045

0.14884758120207758

In [107]:
-math.log(0.40460967519168967)

0.904832441554448